name:               "快,快到碗里来"
description:        "快到碗里来的博客"

url:                ""
author:             "Daniel.Luo"
email:              "winepot2005@gmail.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            "winepot2005@gmail.com"
github:             "github.com/inpot"


background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate