name:               "快,快到碗里来"
description:        "快到碗里来的博客"

url:                "https://inpot.github.io22"
author:             "Daniel.Luo"
email:              "winepot2005@gmail.com"
avatar:             "avatar.jpg"
twitter:            "winepot2005@gmail.com"
github:             "inpot"


background:         "background.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate